# Generated by Django 5.1.6 on 2025-02-15 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stockSimulationApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_ticker", models.CharField(max_length=10)),
                ("date", models.DateField()),
                ("price", models.FloatField()),
                ("open_price", models.FloatField()),
                ("high", models.FloatField()),
                ("low", models.FloatField()),
                ("volume", models.CharField(max_length=50)),
                ("change_percent", models.FloatField()),
            ],
        ),
    ]
