# Generated by Django 5.1.6 on 2025-03-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stockSimulationApp", "0002_stockdata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockdata",
            name="company_ticker",
            field=models.CharField(db_index=True, max_length=10),
        ),
    ]
